sonar.projectKey=Naeomi_Dias_P1_Social_Media
sonar.projectName=Naeomi_Dias_P1_Social_Media

sonar.sources=app
sonar.tests=tests

sonar.exclusions=.venv/**,**/__pycache__/**,uploads/**,logs/**

sonar.python.version=3.12