apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-deployment

spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: flask

  template:
    metadata:
      labels:
        app: flask

    spec:
      containers:
        - name: flask
          image: flask-app:v2
          imagePullPolicy: Never

          ports:
            - containerPort: 5000

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_DATABASE

            - name: DB_USER
              value: root

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: SECRET_KEY

            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: JWT_SECRET_KEY