apiVersion: v1
kind: Secret

metadata:
  name: mysql-secret

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_USER: root
  MYSQL_DB_URL: mysql+pymysql://root:root123@mysql-service:3306/p1_social_media

  SECRET_KEY: 4dfc068632c13981bebdbe23eab3ab89b6e271ed853abf9bcfa757dc61c8577d
  JWT_SECRET_KEY: e9aef8ef479124cac702c50344bd2d8f72fa28c5d154ed279f501d8c49071c50
