apiVersion: v1
kind: Secret

metadata:
  name: mysql-secret

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  MYSQL_USER: root
  MYSQL_DB_URL: mysql+pymysql://root:root123@mysql-service:3306/p1_social_media

  SECRET_KEY: ${SECRET_KEY}
  JWT_SECRET_KEY: ${JWT_SECRET_KEY}
